name: ""
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

image:
  name: ""
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

config:
  data: {}

secret:
  data: {}

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  clusterIp: None

database:
  name: ""
  externalName: ""

resources: {}

livenessProbe: null
readinessProbe: null

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
