{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.name }}
  clusterIP: {{ default "None" .Values.service.clusterIp }}
  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.service.port }}
      protocol: TCP
{{- end }}
