apiVersion: v1
kind: Secret
metadata:
  name: origin-ca-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  key: {{ .Values.cert.originCAKey | b64enc | quote }}
---
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: origin-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: origin-ca-key
      key: key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: origin-ca-certificate
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Values.cert.domain }}
  secretName: origin-ca-secret
  duration: 168h
  renewBefore: 24h
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    name: origin-ca-issuer
    kind: OriginIssuer
