---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    konghq.com/strip-path: "false"
spec:
  ingressClassName: {{ .Values.controller.ingressController.ingressClass }}
  tls:
    - hosts:
        - {{ .Values.cert.domain }}
      secretName: origin-ca-secret
  rules:
    - http:
        paths:
    {{- range .Values.services }}
          - pathType: ImplementationSpecific
            path: {{ print "/" (default .name .path) }}
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .port }}
    {{- end }}
    {{- range .Values.xservices }}
          - pathType: ImplementationSpecific
            path: {{ print "/" (default .name .path) }}
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .port }}
    {{- end }}
