apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.global.environment }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config.data }}
  {{ $key | snakecase | upper }}: {{ $value | quote }}
{{- end }}
