apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.global.environment }}
  labels:
    app: {{ .Values.name }}
    {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      {{- with .Values.serviceAccount.name }}
        {{- printf "serviceAccountName:" | nindent 6 }} {{ . }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          envFrom:
            - configMapRef:
                name: {{.Values.name }}-config
            - secretRef:
                name: {{ .Values.name }}-secret
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
