apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.global.environment }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key | snakecase | upper }}: {{ $value | b64enc | quote }}
{{- end }}
