apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.global.environment }}
  labels:
    app: {{ .Values.name }}
    {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.service.port }}
      protocol: TCP
