apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.primary.persistence.existingClaim }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.global.storageClass }}
  volumeName: {{ .Values.primary.persistence.existingVolume }}
---
