apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huggingface-inference-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: host
  volumeName: huggingface-host-pv-01
