apiVersion: v2
name: databases
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - alias: master
    name: postgresql
    condition: master.enabled
    repository: 'https://charts.bitnami.com/bitnami'
    version: 14.3.1

  - alias: slave
    name: postgresql
    condition: slave.enabled
    repository: 'https://charts.bitnami.com/bitnami'
    version: 14.3.1
